<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class NoticeOrNewsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('notice_or_news')->truncate();
        DB::table('notice_or_news')->insert([
            array('id' => '1','type' => '2','show_in' => '3','published_at' => '2022-01-03 00:00:00','archived_at' => NULL,'title_en' => 'Computer circular has started','title' => 'কম্পিউটার সার্কুলার শুরু হয়েছে','institute_id' => '2','organization_id' => NULL,'industry_association_id' => NULL,'details' => NULL,'details_en' => NULL,'main_image_path' => 'https://file-phase1.nise.gov.bd/uploads/fS3aBIHTUHysbHBhcmlLohdxN8oXSS1641890506.jpg','grid_image_path' => NULL,'thumb_image_path' => NULL,'image_alt_title_en' => NULL,'image_alt_title' => NULL,'file_path' => NULL,'file_alt_title_en' => NULL,'file_alt_title' => NULL,'row_status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2022-01-12 02:41:57','updated_at' => '2022-01-12 02:43:34','deleted_at' => NULL),
            array('id' => '2','type' => '1','show_in' => '3','published_at' => '2022-02-01 00:00:00','archived_at' => NULL,'title_en' => 'Notification has been published.','title' => 'বিজ্ঞপ্তি প্রকাশ করা হয়েছে।','institute_id' => '2','organization_id' => NULL,'industry_association_id' => NULL,'details' => NULL,'details_en' => NULL,'main_image_path' => 'https://file-phase1.nise.gov.bd/uploads/w0vU9GIrxZezZwKs7C0yOa6JEETzhM1644215978.jpg','grid_image_path' => NULL,'thumb_image_path' => NULL,'image_alt_title_en' => NULL,'image_alt_title' => 'abc','file_path' => NULL,'file_alt_title_en' => NULL,'file_alt_title' => NULL,'row_status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2022-02-08 00:39:55','updated_at' => '2022-02-08 00:39:55','deleted_at' => NULL),
            array('id' => '3','type' => '2','show_in' => '3','published_at' => '2022-02-07 00:00:00','archived_at' => NULL,'title_en' => 'There will be cultural events','title' => 'সাংস্কৃতিক অনুষ্ঠান হবে','institute_id' => '1','organization_id' => NULL,'industry_association_id' => NULL,'details' => NULL,'details_en' => NULL,'main_image_path' => 'https://file-phase1.nise.gov.bd/uploads/rkqXYlkfuKWhiK19voAttUXqe23K8e1644234493.jpg','grid_image_path' => NULL,'thumb_image_path' => NULL,'image_alt_title_en' => NULL,'image_alt_title' => NULL,'file_path' => NULL,'file_alt_title_en' => NULL,'file_alt_title' => NULL,'row_status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2022-02-08 05:48:25','updated_at' => '2022-02-08 05:48:25','deleted_at' => NULL),
            array('id' => '4','type' => '1','show_in' => '5','published_at' => '2022-02-07 00:00:00','archived_at' => NULL,'title_en' => 'Notification has been published.','title' => 'বিজ্ঞপ্তি প্রকাশ করা হয়েছে।','institute_id' => NULL,'organization_id' => NULL,'industry_association_id' => '1','details' => NULL,'details_en' => NULL,'main_image_path' => 'https://file-phase1.nise.gov.bd/uploads/LcnNfbzNn4cGB2HX74ly84y1Vlmecv1644234875.jpg','grid_image_path' => NULL,'thumb_image_path' => NULL,'image_alt_title_en' => NULL,'image_alt_title' => NULL,'file_path' => NULL,'file_alt_title_en' => NULL,'file_alt_title' => NULL,'row_status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2022-02-08 05:54:41','updated_at' => '2022-02-08 05:54:41','deleted_at' => NULL),
            array('id' => '5','type' => '1','show_in' => '5','published_at' => '2022-02-10 00:00:00','archived_at' => NULL,'title_en' => 'Freelancing courses are no longer available this fiscal year','title' => 'এই অর্থবছরের আর ফ্রিল্যান্সিং কোর্স হচ্ছে না','institute_id' => NULL,'organization_id' => NULL,'industry_association_id' => '2','details' => NULL,'details_en' => NULL,'main_image_path' => 'https://file-phase1.nise.gov.bd/uploads/S5aKWed7wWVueMBHFz4zfHJiGfnVhA1644234920.png','grid_image_path' => NULL,'thumb_image_path' => NULL,'image_alt_title_en' => NULL,'image_alt_title' => NULL,'file_path' => NULL,'file_alt_title_en' => NULL,'file_alt_title' => NULL,'row_status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2022-02-08 05:55:26','updated_at' => '2022-02-08 05:55:26','deleted_at' => NULL),
            array('id' => '6','type' => '1','show_in' => '3','published_at' => '2022-02-08 00:00:00','archived_at' => NULL,'title_en' => NULL,'title' => 'কম্পিউটার সার্কুলার','institute_id' => '1','organization_id' => NULL,'industry_association_id' => NULL,'details' => NULL,'details_en' => NULL,'main_image_path' => 'https://file-phase1.nise.gov.bd/uploads/fadWoDkNDVSFVD8vcORPYSgdHZ8z1N1644234974.png','grid_image_path' => NULL,'thumb_image_path' => NULL,'image_alt_title_en' => NULL,'image_alt_title' => NULL,'file_path' => 'https://file.nise3.xyz/uploads/2WYzb6e6E0NqVC0Rsq78L9uK0lYLkE1644234965.pdf','file_alt_title_en' => NULL,'file_alt_title' => NULL,'row_status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2022-02-08 05:56:21','updated_at' => '2022-02-08 05:56:21','deleted_at' => NULL),
            array('id' => '7','type' => '2','show_in' => '3','published_at' => '2022-02-07 00:00:00','archived_at' => NULL,'title_en' => 'Allocations are being distributed','title' => 'বরাদ্ধ বিতরণ হচ্ছে','institute_id' => '1','organization_id' => NULL,'industry_association_id' => NULL,'details' => NULL,'details_en' => NULL,'main_image_path' => 'https://file-phase1.nise.gov.bd/uploads/r79dZKLqTT2bB7F2rqSEvFMJITaXWC1644235016.jpg','grid_image_path' => NULL,'thumb_image_path' => NULL,'image_alt_title_en' => NULL,'image_alt_title' => NULL,'file_path' => NULL,'file_alt_title_en' => NULL,'file_alt_title' => NULL,'row_status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2022-02-08 05:57:01','updated_at' => '2022-02-08 05:57:01','deleted_at' => NULL),
            array('id' => '8','type' => '1','show_in' => '3','published_at' => '2022-02-08 00:00:00','archived_at' => NULL,'title_en' => 'Computer training is starting','title' => 'কম্পিউটার প্রশিক্ষণ শুরু হচ্ছে','institute_id' => '1','organization_id' => NULL,'industry_association_id' => NULL,'details' => NULL,'details_en' => NULL,'main_image_path' => 'https://file-phase1.nise.gov.bd/uploads/pydUNs9Qk0kZnuy4kb9BaYVjdP7OuM1644235052.jpg','grid_image_path' => NULL,'thumb_image_path' => NULL,'image_alt_title_en' => NULL,'image_alt_title' => NULL,'file_path' => NULL,'file_alt_title_en' => NULL,'file_alt_title' => NULL,'row_status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2022-02-08 05:57:38','updated_at' => '2022-02-08 05:57:38','deleted_at' => NULL),
            array('id' => '9','type' => '1','show_in' => '5','published_at' => '2022-02-10 00:00:00','archived_at' => NULL,'title_en' => 'Rally','title' => 'সমাবেশ','institute_id' => NULL,'organization_id' => NULL,'industry_association_id' => '1','details' => NULL,'details_en' => NULL,'main_image_path' => 'https://file-phase1.nise.gov.bd/uploads/vMohFcn5TLuUiAmgUyZ9qClXYu0rpX1644470628.jpeg','grid_image_path' => NULL,'thumb_image_path' => NULL,'image_alt_title_en' => NULL,'image_alt_title' => NULL,'file_path' => NULL,'file_alt_title_en' => NULL,'file_alt_title' => NULL,'row_status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2022-02-10 17:24:21','updated_at' => '2022-02-14 21:27:22','deleted_at' => NULL),
            array('id' => '10','type' => '2','show_in' => '5','published_at' => '2022-02-14 00:00:00','archived_at' => NULL,'title_en' => 'Awards','title' => 'পুরস্কার','institute_id' => NULL,'organization_id' => NULL,'industry_association_id' => '2','details' => NULL,'details_en' => NULL,'main_image_path' => 'https://file-phase1.nise.gov.bd/uploads/sJuGme8fEWj117p1LsTaiQBKK3gojr1644470697.jpg','grid_image_path' => NULL,'thumb_image_path' => NULL,'image_alt_title_en' => NULL,'image_alt_title' => NULL,'file_path' => NULL,'file_alt_title_en' => NULL,'file_alt_title' => NULL,'row_status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2022-02-10 17:25:37','updated_at' => '2022-02-15 00:04:51','deleted_at' => NULL),
            array('id' => '11','type' => '1','show_in' => '1','published_at' => '2022-02-10 00:00:00','archived_at' => NULL,'title_en' => 'New Vacancies','title' => 'নতুন শূন্যপদ','institute_id' => NULL,'organization_id' => NULL,'industry_association_id' => NULL,'details' => NULL,'details_en' => NULL,'main_image_path' => 'https://file-phase1.nise.gov.bd/uploads/fdKQPJF9g9rrmfdmodDALat3qzKin51644475144.jpg','grid_image_path' => NULL,'thumb_image_path' => NULL,'image_alt_title_en' => NULL,'image_alt_title' => NULL,'file_path' => NULL,'file_alt_title_en' => NULL,'file_alt_title' => NULL,'row_status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2022-02-10 18:39:21','updated_at' => '2022-02-10 18:39:21','deleted_at' => NULL),
            array('id' => '12','type' => '1','show_in' => '1','published_at' => '2022-02-11 00:00:00','archived_at' => NULL,'title_en' => 'New Opportunities','title' => 'নতুন সুযোগ','institute_id' => NULL,'organization_id' => NULL,'industry_association_id' => NULL,'details' => NULL,'details_en' => NULL,'main_image_path' => 'https://file-phase1.nise.gov.bd/uploads/CPglJ0jEGkdEWD4wXW877aLMbjp3E91644475441.jpg','grid_image_path' => NULL,'thumb_image_path' => 'https://file-phase1.nise.gov.bd/uploads/uDFcxERXkHXEtT0K3xlCeYEp006h4h1644475457.jpg','image_alt_title_en' => NULL,'image_alt_title' => NULL,'file_path' => 'https://file-phase1.nise.gov.bd/uploads/aoOvVMXrtOnDxY4AGm5SxZYccqtKg81644475511.pdf','file_alt_title_en' => NULL,'file_alt_title' => NULL,'row_status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2022-02-10 18:45:15','updated_at' => '2022-02-10 18:45:44','deleted_at' => NULL),
            array('id' => '13','type' => '1','show_in' => '1','published_at' => '2022-02-10 00:00:00','archived_at' => NULL,'title_en' => 'Circulars','title' => 'বিজ্ঞপ্তি','institute_id' => NULL,'organization_id' => NULL,'industry_association_id' => NULL,'details' => NULL,'details_en' => NULL,'main_image_path' => 'https://file-phase1.nise.gov.bd/uploads/odvF2LA9dycUPaogrdZhTeWJRSi07x1644491304.jpg','grid_image_path' => NULL,'thumb_image_path' => NULL,'image_alt_title_en' => NULL,'image_alt_title' => NULL,'file_path' => 'https://file-phase1.nise.gov.bd/uploads/S3zb9oXWWJw8V3LMlP0SeN884p5Dc41644491272.pdf','file_alt_title_en' => NULL,'file_alt_title' => NULL,'row_status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2022-02-10 23:08:28','updated_at' => '2022-02-10 23:08:28','deleted_at' => NULL),
            array('id' => '14','type' => '1','show_in' => '2','published_at' => '2022-02-14 00:00:00','archived_at' => NULL,'title_en' => 'Circulars','title' => 'বিজ্ঞপ্তি','institute_id' => NULL,'organization_id' => NULL,'industry_association_id' => NULL,'details' => NULL,'details_en' => NULL,'main_image_path' => 'https://file-phase1.nise.gov.bd/uploads/b94CCjap8LZP2ddwtVRFIkG2Ixldbc1644836100.jpg','grid_image_path' => NULL,'thumb_image_path' => NULL,'image_alt_title_en' => NULL,'image_alt_title' => NULL,'file_path' => NULL,'file_alt_title_en' => NULL,'file_alt_title' => NULL,'row_status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2022-02-14 22:55:42','updated_at' => '2022-02-14 22:55:42','deleted_at' => NULL),
            array('id' => '15','type' => '1','show_in' => '2','published_at' => '2022-02-15 00:00:00','archived_at' => NULL,'title_en' => 'Inauguration Ceremony','title' => 'উদ্বোধন অনুষ্ঠান','institute_id' => NULL,'organization_id' => NULL,'industry_association_id' => NULL,'details' => NULL,'details_en' => NULL,'main_image_path' => 'https://file-phase1.nise.gov.bd/uploads/WgLUmYBW4o4ih45Lxr2tOoRgzZULBp1644922132.jpg','grid_image_path' => NULL,'thumb_image_path' => NULL,'image_alt_title_en' => NULL,'image_alt_title' => NULL,'file_path' => NULL,'file_alt_title_en' => NULL,'file_alt_title' => NULL,'row_status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2022-02-15 22:49:56','updated_at' => '2022-02-15 22:50:52','deleted_at' => NULL),
            array('id' => '16','type' => '1','show_in' => '2','published_at' => '2022-02-15 00:00:00','archived_at' => NULL,'title_en' => 'National Youth Day','title' => 'জাতীয় যুব দিবস','institute_id' => NULL,'organization_id' => NULL,'industry_association_id' => NULL,'details' => NULL,'details_en' => NULL,'main_image_path' => 'https://file-phase1.nise.gov.bd/uploads/GiJ4w6BIGcKe4PRrS0dHlZU6RkNIzL1644922765.jpg','grid_image_path' => 'https://file-phase1.nise.gov.bd/uploads/01CiWsBFC4KFcJyxcVWzFE9CuH6sz01644924189.jpg','thumb_image_path' => 'https://file-phase1.nise.gov.bd/uploads/gKz9rl2wPxLXonlHaivHFs7SfL9xhr1644924185.jpg','image_alt_title_en' => NULL,'image_alt_title' => NULL,'file_path' => NULL,'file_alt_title_en' => NULL,'file_alt_title' => NULL,'row_status' => '1','created_by' => NULL,'updated_by' => NULL,'created_at' => '2022-02-15 22:59:48','updated_at' => '2022-02-16 00:34:27','deleted_at' => NULL)
        ]);
        Schema::disableForeignKeyConstraints();

    }
}
